"""Add email_settings table

Revision ID: aa117e34eb9f
Revises: 9b2c1f4a0d7e
Create Date: 2026-03-08 21:49:09.757574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa117e34eb9f'
down_revision: Union[str, None] = '9b2c1f4a0d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('GMAIL', 'OUTLOOK', name='emailprovider'), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_email_settings_id'), 'email_settings', ['id'], unique=False)
    op.drop_constraint('labels_name_key', 'labels', type_='unique')
    op.drop_index('ix_labels_name', table_name='labels')
    op.create_index(op.f('ix_labels_name'), 'labels', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labels_name'), table_name='labels')
    op.create_index('ix_labels_name', 'labels', ['name'], unique=False)
    op.create_unique_constraint('labels_name_key', 'labels', ['name'])
    op.drop_index(op.f('ix_email_settings_id'), table_name='email_settings')
    op.drop_table('email_settings')
    # ### end Alembic commands ###
