"""Add due_date to issues

Revision ID: c32ebb38d2c5
Revises: e5c4bf3f9cb3
Create Date: 2026-01-13 13:33:45.971341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32ebb38d2c5'
down_revision: Union[str, None] = 'e5c4bf3f9cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'due_date')
    # ### end Alembic commands ###
