"""add email_automation_enabled to users

Revision ID: f36a00cef9b1
Revises: 9e03a32fc667
Create Date: 2026-03-08 23:13:39.619032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36a00cef9b1'
down_revision: Union[str, None] = '9e03a32fc667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_automation_enabled', sa.Boolean(), nullable=True))
    # Fill existing users with default value
    op.execute("UPDATE users SET email_automation_enabled = TRUE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_automation_enabled')
    # ### end Alembic commands ###

